GET http://localhost:3000/users?role=client

####

POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"Akash Chaudhary",
    "phoneNumber":"9923456162",
    "email":"akash@gmail.com",
    "role":"client"
}

####

DELETE http://localhost:3000/users/659ee1fcb4da7abbe3df9a89

